### ISSUE TITLE
state_notifierの導入

### ISSUE THREAD

**Issue by ho2ri2s** [CA21engineer/morning-weakers#16]
## 行うこと
- [ ] state_notifierの導入 #16

## 参考ページ
- [itomeさんblog](https://itome.team/blog/2020/05/flutter-state-notifier-provider/)
- [state_notifier](https://pub.dev/packages/state_notifier)
- [qiita](https://qiita.com/_masaokb/items/fe77495db0aeba226d2a)
## その他 共有事項

**Comment by zoothezoo** [comment]
完璧です
