### ISSUE TITLE
Androidのgoogle_sign_inで必要な設定を追加(google-services.json )

### ISSUE THREAD

**Issue by tomu28** [CA21engineer/morning-weakers#48]
## 行うこと
- [ ] Androidのgoogle_sign_inで必要な設定を追加(google-services.json )

## その他 共有事項
- iOSのみAuth動作確認
  - ref: #44

**Comment by zoothezoo** [comment]
- SHA1をfirebase consoleに追加するだけでできたよ

<img width="310" alt="スクリーンショット 2020-06-12 1 08 25" src="https://user-images.githubusercontent.com/38239244/84411897-6a0c4300-ac49-11ea-9318-8a313c962f23.png">
